apiVersion: v1
kind: Service
metadata:
  name: front-end

spec:
  selector:
    app: front-end

  ports:
    - name: http
      port: 80
      nodePort: 80

    - name: endpoint
      port: 80

  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway

spec:
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080
      nodePort: 8080

    - name: endpoint
      port: 8080

  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: va-bca

spec:
  selector:
    app: va-bca

  ports:
    - name: http
      port: 8080
      nodePort: 30010

    - name: endpoint
      port: 30010

  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: va-permata

spec:
  selector:
    app: va-permata

  ports:
    - name: http
      port: 8080
      nodePort: 30020

    - name: endpoint
      port: 30020

  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: va-cimb

spec:
  selector:
    app: va-cimb

  ports:
    - name: http
      port: 8080
      nodePort: 30030

    - name: endpoint
      port: 30010

  type: NodePort
