apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  selector:
    matchLabels:
      app: front-end
  replicas: 2
  template: 
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: rachmathidayat/front-end:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 2
  template: 
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: rachmathidayat/api-gateway:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 2
  template: 
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: rachmathidayat/api-gateway:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: va-bca
spec:
  selector:
    matchLabels:
      app: va-bca
  replicas: 2
  template: 
    metadata:
      labels:
        app: va-bca
    spec:
      containers:
      - name: va-bca
        image: rachmathidayat/va-bca:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: va-permata
spec:
  selector:
    matchLabels:
      app: va-permata
  replicas: 2
  template: 
    metadata:
      labels:
        app: va-permata
    spec:
      containers:
      - name: va-permata
        image: rachmathidayat/va-permata:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: va-cimb
spec:
  selector:
    matchLabels:
      app: va-cimb
  replicas: 2
  template: 
    metadata:
      labels:
        app: va-cimb
    spec:
      containers:
      - name: va-cimb
        image: rachmathidayat/va-cimb:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-node1
spec:
  selector:
    matchLabels:
      app: mongo-node1
  replicas: 1
  template: 
    metadata:
      labels:
        app: mongo-node1
    spec:
      containers:
      - name: mongo-node1
        image: rachmathidayat/mongo-node1:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-node2
spec:
  selector:
    matchLabels:
      app: mongo-node2
  replicas: 1
  template: 
    metadata:
      labels:
        app: mongo-node2
    spec:
      containers:
      - name: mongo-node2
        image: rachmathidayat/mongo-node2:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-node3
spec:
  selector:
    matchLabels:
      app: mongo-node3
  replicas: 1
  template: 
    metadata:
      labels:
        app: mongo-node3
    spec:
      containers:
      - name: mongo-node3
        image: rachmathidayat/mongo-node3:latest
